$(document).ready(function(){
    $(".panel-title a").click(function(){
        $(this).parents(".panel-default").siblings(".panel-default").find(".panel-title").removeClass("open");
        $(this).parent(".panel-title").toggleClass("open");
    });
    $(".ozy-grid-gallery li a").mouseenter(function(){
        $(this).children("img.transform").css({"transform":"matrix(1, 0, 0, 1, 0, -60)"});
        $(this).children(".info.transform").css({"top":"0", "right":"0"});
    });
    $(".ozy-grid-gallery li a").mouseleave(function(){
        $(this).children("img.transform").css({"transform":"matrix(1, 0, 0, 1, 0, 0)"});
        $(this).children(".info.transform").css({"top":"100%", "right":"0"});
    });
    $(".dropdown").hover(function(){$(window).width() >= 750 && $(this).toggleClass("open")}), $(".search-icon").click(function(){$("#top-search").toggleClass("open")}), $(window).width() > 767 && $(".item-heading").click(function(){$(this).siblings(".item-desc").slideToggle()}), $(".menu-item-request-rate").click(function(){$("#request-a-rate").slideToggle()}), $("#close-btn").click(function(){$("#request-a-rate").slideToggle()}), $("#close-search").click(function(){$("#top-search").toggleClass("open")}), $(".menu-btn").click(function(){$(this).toggleClass("menu-opened")}), $(window).scroll(function(){$(this).scrollTop() > 150?$("#go-to-top").fadeIn():$("#go-to-top").fadeOut()}), $("#go-to-top").click(function(){return $("html, body").animate({scrollTop:0}, 800), !1}), $(".board-tabs a").click(function(o){o.preventDefault(), $(this).tab("show")}); var o = $(window).width(); $(window).bind("resize", function(){location.reload(), 768 > o?($("#mytabs").removeClass("navbar"), $("#mytabs").addClass("nav-tabs")):$("#mytabs").addClass("navbar")})}), $(function(){$(".jcarousel").jcarouselAutoscroll()}), function(o){o(function(){var t = o(".jcarousel"); t.on("jcarousel:reload jcarousel:create", function(){var t = o(this), n = t.innerWidth(); n >= 600?n /= 3:n >= 350 && (n /= 2), t.jcarousel("items").css("width", Math.ceil(n) + "px")}).jcarousel({wrap:"circular"}), o(".jcarousel-control-prev").jcarouselControl({target:"-=1"}), o(".jcarousel-control-next").jcarouselControl({target:"+=1"}), o(".jcarousel-pagination").on("jcarouselpagination:active", "a", function(){o(this).addClass("active")}).on("jcarouselpagination:inactive", "a", function(){o(this).removeClass("active")}).on("click", function(o){o.preventDefault()}).jcarouselPagination({perPage:1, item:function(o){return'<a href="#' + o + '">' + o + "</a>"}})})}(jQuery), function(o){o(function(){o(".verticle-slider").jcarousel({vertical:!0, size:5}), o(".jcarousel-control-prev").on("jcarouselcontrol:active", function(){o(this).removeClass("inactive")}).on("jcarouselcontrol:inactive", function(){o(this).addClass("inactive")}).jcarouselControl({target:"-=1"}), o(".jcarousel-control-next").on("jcarouselcontrol:active", function(){o(this).removeClass("inactive")}).on("jcarouselcontrol:inactive", function(){o(this).addClass("inactive")}).jcarouselControl({target:"+=1"}), o(".jcarousel-pagination").on("jcarouselpagination:active", "a", function(){o(this).addClass("active")}).on("jcarouselpagination:inactive", "a", function(){o(this).removeClass("active")}).jcarouselPagination()})}(jQuery);